config/routes.rb
Rails.application.routes.draw do
  root 'home#home'
  get '/about', to: 'home#about'

  resources :contents
  resources :users

  #sign in routes
  get '/sign_in', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy', as: 'delete'

  mount Messenger::Engine, at: "/messenger"

  get '/texty/send_text', to: "texty#new_text"
  patch '/send_text', to: 'texty#send_text'

  post '/instant_boozt', to: "users#instant_boozt"
  post '/add_content_category', to: "contents#add_content_category"

  
end


# Messenger Bot Routes
# Messenger::Engine.routes.draw do
#   get  :subscribe, to: "messenger#subscribe"
#   get  :webhook,   to: "messenger#validate"
# end

# Rails.application.routes.draw do
#   post 'messenger/webhook', to: "messenger#webhook"
# end

app/models/content.rb
class Content < ActiveRecord::Base
	has_many :boozts, dependent: :destroy
	has_many :users, through: :boozts

	## giphy
	def self.get_GIPHY_data (category)
		category_data = category.split("+")
		response = HTTParty.get('http://api.giphy.com/v1/gifs/search?q=' + category + '&api_key=dc6zaTOxFJmzC&fmt=json')
		response["data"].each do |content|
			url = content["images"]["fixed_height"]["url"]
			Content.create({
				title: category_data[0] + " " + category_data[1],
	            url: url,
	            category: "GIF",
	            sentiment: category_data[0]
				})
		end
	end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_content_category
    category = params["category"]
    Content.get_GIPHY_data (category)
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:title, :url, :category, :sentiment)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :sentiment %><br>
    <%= f.text_field :sentiment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <h5 style="color: white; text-align: center">Add categories for content</h5>
  <div class="col s6 offset-s3">
    <%= form_tag("/add_content_category", method: "post") do %>
      <%= label_tag(:category, "Category") %>
      <%= text_field_tag(:category) %>
      <%= submit_tag("Add category") %>
    <% end %>
  </div>
</div>

<br><br><br>
<div class="row">

  <h1>Listing Contents</h1>
  <% @contents.each do |content| %>
    <div class="col s3" style="display: block; text-align: center">
      <img src="<%= content.url %>" style="width: 100%">
      <p style="text-align: center"><%= content.id %></p>
      <%= link_to 'Show', content %>
      <%= link_to 'Destroy', content, method: :delete %>
    </div>
  <% end %>

</div>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @content.title %>
</p>

<img src="<%= @content.url %>" style="height: 250px; width: 250px">

<p>
  <strong>Category:</strong>
  <%= @content.category %>
</p>

<p>
  <strong>Sentiment:</strong>
  <%= @content.sentiment %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>