config/routes.rb
Rails.application.routes.draw do
  root 'home#home'
  get '/about', to: 'home#about'

  resources :contents
  resources :users

  #sign in routes
  get '/sign_in', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy', as: 'delete'

  mount Messenger::Engine, at: "/messenger"

  get '/texty/send_text', to: "texty#new_text"
  patch '/send_text', to: 'texty#send_text'

  post '/instant_boozt', to: "users#instant_boozt"
  post '/add_content_category', to: "contents#add_content_category"

  
end


# Messenger Bot Routes
# Messenger::Engine.routes.draw do
#   get  :subscribe, to: "messenger#subscribe"
#   get  :webhook,   to: "messenger#validate"
# end

# Rails.application.routes.draw do
#   post 'messenger/webhook', to: "messenger#webhook"
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  # def authenticate_user
  #   if !current_user
  #     redirect_to sign_in_path, notice: "You must be signed in to do that!"
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
 <footer class="page-footer" style="background-color: #f05d23;">
    <div class="container">
      <div class="row">

        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li style="font-size: 10px !important"><a class="white-text link" href="http://www.github.com/emiliogomezlavin"><i class="fi-social-github"></i>&nbspGithub</a></li>
            <li><a class="white-text link" href="http://www.linkedin.com/in/emiliogomezlavin"><i class="fi-social-linkedin"></i>&nbspLinkedIn</a></li>
            <li><a class="white-text link" href="https://www.facebook.com/emilio.lavin"><i class="fi-social-facebook"></i>&nbspFacebook</a>
            </li><li><a class="white-text link" href="https://twitter.com/emiliogomlav"><i class="fi-social-twitter"></i>&nbspTwitter</a></li>
          </ul>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Boozt Recommends</h5>
          <ul>
            <li><a class="white-text link" href="http://www.goodnewsnetwork.org/">Good News Network</a></li>
            <li><a class="white-text link" href="http://tinybuddha.com/">Tiny Buddha</a></li>
            <li><a class="white-text link" href="http://www.ted.com/">TED</a></li>
            <li><a class="white-text link" href="http://1000awesomethings.com/">1000 Awesome Things</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container" style="text-align: center; font-size: 15px">
      Made with <i class="material-icons">favorite</i> by <a style="color: #326273" href="http://www.github.com/emiliogomezlavin">  &nbsp Emilio Gomez Lavin</a>
      </div>
    </div>
  </footer>

app/views/application/_header.html.erb
 
<nav class="my-nav-bar">
  <div class="nav-wrapper"> 
    <a href="/" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down menu-titles">
      <li><a href="/about" class="nav-bar-title">ABOUT</a></li>
      <% if current_user %>
        <li><%= link_to 'PROFILE', user_path(current_user), method: :get, class: "nav-bar-title" %></li>
        <li><%= link_to "SIGN OUT", sessions_path, method: :delete, class: "nav-bar-title"%></li>
      <% else %>
        <li><%= link_to "SIGN IN", sign_in_path, method: :get, class: "nav-bar-title" %></li>
        <li><%= link_to "SIGN UP", new_user_path, method: :get, class: "nav-bar-title" %></li>
      <% end %>
    </ul>
    <ul id="mobile-demo" class="side-nav">
      <li><a class="side-titles" href="/about">ABOUT</a></li>
      <% if current_user %>
      <li><%= link_to 'PROFILE', user_path(current_user), method: :get, class: "side-titles" %></li>
      <li><%= link_to "SIGN OUT", sessions_path, method: :delete, class: "side-titles" %></li>
    <% else %>
      <li><%= link_to "SIGN IN", sign_in_path, method: :get, class: "side-titles" %></li>
      <li><%= link_to "SIGN UP", new_user_path, method: :get, class: "side-titles" %></li>
    <% end %>
    </ul>
  </div>
</nav>